### ISSUE TITLE
Support for TRPC 11

### ISSUE THREAD

**Issue by LeonAlvarez** [Vercjames/package-trpc-swagger#11]
It would be good to have support for trpc v11, it's not out yet, but rc is and is already the default version on docs.

**Comment by Vercjames** [comment]
Release Candidate just came out. It's certainly something I'm keep on tackling.

**Comment by Vercjames** [comment]
Keeping a pulse on this issue. as of today trpc is on version v11.0.0-rc.366.

https://github.com/trpc/trpc

**Comment by lvl99wzrd** [comment]
Is there any temporary workaround to make trpc-swagger v1.2.3 works on trpc v11.0.0-rc.366?

**Comment by jbgrunewald** [comment]
Definitely confused to see this, because the readme says to have trpc server 11 installed. Am I misunderstanding something? I do see the example using the app router is using v10.

**Comment by samjcombs** [comment]
agreed, this should be updated to `v10` https://github.com/Vercjames/package-trpc-swagger/blob/5bcf7a8ddba4090cf0de9effffc029663f3a51cd/README.md?plain=1#L142

being on v11 results in errors like this: 
```
"source":"server","message":"Unknown procedure type","stack":"Error: Unknown procedure type\n    at getProcedureType (/<REDACTED>/node_modules/trpc-swagger/build/utils/procedure.js:29:11)
````

**Comment by waptik** [comment]
I'm using trpc v11 and looking at this issue, i think i'll wait until there's an official support for it before i use it

**Comment by Vercjames** [comment]
Still waiting on the official release for v11

the official NPM packages are on 10.45.2 
https://www.npmjs.com/package/@trpc/server
https://www.npmjs.com/package/@trpc/client

I here the communities cry for v11 support. It's at the top of my list.

**Comment by Vercjames** [comment]
> agreed, this should be updated to `v10`
> 
> https://github.com/Vercjames/package-trpc-swagger/blob/5bcf7a8ddba4090cf0de9effffc029663f3a51cd/README.md?plain=1#L142
> 
> being on v11 results in errors like this:
> 
> ```
> "source":"server","message":"Unknown procedure type","stack":"Error: Unknown procedure type\n    at getProcedureType (/<REDACTED>/node_modules/trpc-swagger/build/utils/procedure.js:29:11)
> ```

Updated. But feel free to submit PR's <3

**Comment by Vercjames** [comment]
If you MUST have support for v11. I was able to get this patch package work for trpc 11. 

Add this to your package.json
[patch-package](https://github.com/ds300/patch-package)

Then apply this patch
[trpc-openapi+1.2.0.patch](https://github.com/jlalmes/trpc-openapi/files/14226232/trpc-openapi%2B1.2.0.patch)

**Comment by musjj** [comment]
Would really appreciate it if you can make a branch/PR for trpc v11 support while we wait for the official release. Patches are nice, but it's also really fragile.

**Comment by denvey** [comment]
> If you MUST have support for v11. I was able to get this patch package work for trpc 11.如果您必须支持 v11。我能够让这个补丁包适用于 trpc 11。
> 
> Add this to your package.json将其添加到您的package.json [patch-package 补丁包](https://github.com/ds300/patch-package)
> 
> Then apply this patch 然后应用此补丁 [trpc-openapi+1.2.0.patchtrpc-openapi+1.2.0.补丁](https://github.com/jlalmes/trpc-openapi/files/14226232/trpc-openapi%2B1.2.0.patch)

This patch package is for trpc-openapi, is there a patch package for trpc-swagger?

**Comment by dBianchii** [comment]
@Vercjames thanks for the continued work on this fork :heart: 

Let's all hope V11 gets released soon

**Comment by Vercjames** [comment]
Still on v10 [trpc](https://www.npmjs.com/package/@trpc/server)

**Comment by Vercjames** [comment]
Still keeping tabs on this <3

**Comment by Vercjames** [comment]
Still on v10 [trpc](https://www.npmjs.com/package/@trpc/server)

**Comment by flawnn** [comment]
> > If you MUST have support for v11. I was able to get this patch package work for trpc 11.如果您必须支持 v11。我能够让这个补丁包适用于 trpc 11。
> > Add this to your package.json将其添加到您的package.json [patch-package 补丁包](https://github.com/ds300/patch-package)
> > Then apply this patch 然后应用此补丁 [trpc-openapi+1.2.0.patchtrpc-openapi+1.2.0.补丁](https://github.com/jlalmes/trpc-openapi/files/14226232/trpc-openapi%2B1.2.0.patch)
> 
> This patch package is for trpc-openapi, is there a patch package for trpc-swagger?

@Vercjames - What about this?

**Comment by Vercjames** [comment]
@flawnn, I briefly explored this approach, and you're welcome to use `patch-package` for your current project. Since it's an npm package, this method is more suitable for individual projects rather than being part of the core repository.

All the TRPC packages are still marked for v10.45.2:

[@trpc/server](https://www.npmjs.com/package/@trpc/server)
[@trpc/client](https://www.npmjs.com/package/@trpc/client)
[@trpc/next](https://www.npmjs.com/package/@trpc/next)

According to the official [TRPC Migration Docs](https://trpc.io/docs/migrate-from-v10-to-v11):

> "The functionality is stable and can be used in production, but we may make small breaking API changes between patches until we reach 11.0.0."


Since this repository relies on those patch changes, I need to wait for v11 to be released to ensure compatibility with their specifications. Here's the current plan:

1. Wait for 11.0.0 to be published on npm.
2. Review the new specifications and functionality.
3. Develop v2.0.0 of this repository.
4. Build example apps for popular frameworks.
5. Create new Jest scripts to detect any changes TRPC makes.

I understand it’s frustrating to wait. Many core projects (React v19, TRPC v11, Next.js v15) have faced challenges in getting their new releases up to standard. This is a natural part of the process when ensuring robust and reliable software. I have great respect for all the developers working on these projects, and if any of them have insights or suggestions, I’d be happy to welcome experienced developers as active contributors.

**Comment by adriangonzy** [comment]
> > > If you MUST have support for v11. I was able to get this patch package work for trpc 11.如果您必须支持 v11。我能够让这个补丁包适用于 trpc 11。
> > > Add this to your package.json将其添加到您的package.json [patch-package 补丁包](https://github.com/ds300/patch-package)
> > > Then apply this patch 然后应用此补丁 [trpc-openapi+1.2.0.patchtrpc-openapi+1.2.0.补丁](https://github.com/jlalmes/trpc-openapi/files/14226232/trpc-openapi%2B1.2.0.patch)
> > 
> > 
> > This patch package is for trpc-openapi, is there a patch package for trpc-swagger?
> 
> @Vercjames - What about this?

In case this can be useful @flawnn, I created my own patch for the trpc-swagger package. But I used pnpm patching which is native. The patch seems to be the same format as the ones from patch-package, so maybe it can work. 

[trpc-swagger@1.2.6.patch](https://github.com/user-attachments/files/17946807/trpc-swagger%401.2.6.patch)
